parameters:
    assetpicker.console_listener.class:  Netresearch\AssetPickerBundle\Listener\ConsoleListener
    assetpicker.twig.class:              Netresearch\AssetPickerBundle\Twig\AssetPickerExtension

services:
    assetpicker.console_listener:
        class: '%assetpicker.console_listener.class%'
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: onCommandTerminate }
    assetpicker.twig_extension:
        class: '%assetpicker.twig.class%'
        arguments:
            - '@service_container'
            - '@router'
        tags:
            - { name: twig.extension }